name: main
on:
  schedule:
    - cron: "*/45 * * * *"
  workflow_dispatch:

jobs:
  schedule:
    name: ping
    runs-on: ubuntu-latest
    steps:
      - name: Ping homepage
        run: wget https://cinerama-ypsj.onrender.com
