on: workflow_dispatch

jobs:
  workflow_dispatch:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Ping homepage
        run: wget https://cinerama-ypsj.onrender.com
